### ISSUE TITLE
关于论文中使用的SimGCL baseline在Epinions数据集中，recall@20的数值问题

### ISSUE THREAD

**Issue by spnooyseed** [huachzhou/APDA#1]
首先您的工作非常的新颖，让人眼前一亮，很有创新性。然后想要去实际测一下您代码的正确性；
但是发现了一些比较严重的问题:
1. 发现您代码里面提供的计算逆受欢迎系数的公式与论文提供的不符合，并且使用论文提供的公式去计算的话，Epinions数据集上recall@20只能跑到0.11多，论文中描述这个公式可以达到0.126
2. baseline SimGCL这个方法在Epinions数据集上recall@20只有0.1189，根据您代码里面的嵌入维度设置为256，最大epoch为50 ， 学习率为0.001， 卷积层数为2层，然后对比学习的损失权重为0.2，这样都可以跑到recall@20 = 0.1315 ， 您是否有故意调低baseline的行为呢。

**Comment by huachzhou** [comment]
同学你好，非常感谢你对我们work的关注，这是一个一年前的工作，可能有些细节记不太清楚了，但我希望我能最大程度解决您的问题。首先是第一个问题的话，就是逆受欢迎系数公式您看实现上哪里不太符合呢，如果跑我们的实现的话应该是能跑到我们公布的数字的，如果跑我们实现没有得到我们数字的话，您可以回复我，我再check一下或者跟您再对一下。
第二个问题的话，SimGCL确实是一个很强的baseline，我们做的topic是流行度去偏，这里SimGCL以及GTN做出来的时候不是一个流行度去偏的baseline，我们当时调参的时候SimGCL和GTN除了原始文章中默认的超参数，其他超参数调整更关注去偏的效果就是PRU那个指标。然后加上这两个baseline是想说，如果从去偏考虑模型的性能的话，我们的模型是能做到比较不错的去偏，并且有一些不错的准确性上的效果。

希望我的回复能解决你的问题，如果回复不及时的话，还请您谅解

**Comment by spnooyseed** [comment]
非常感谢您的回复。
1. 您代码中提供的逆受欢迎系数的计算公式为：
![image](https://github.com/huachzhou/APDA/assets/55803010/70c6e521-13dd-4b3d-b2f6-bcb0b009b126)
论文中的公式为：
![image](https://github.com/huachzhou/APDA/assets/55803010/37f352e4-f937-4ec2-a707-b262ea3e503f)
![image](https://github.com/huachzhou/APDA/assets/55803010/2096721f-18d9-44e1-a4b3-cb3d10aff3f5)

您代码中实现的明显不一样
2. SimGCL baseline的问题，即便您更关注PRU指标，但是作为baseline这个也不能不调参吧，而且SimGCL原文是嵌入维度为64，20 个epoch，您这个使用了256维度，以及50 epoch，这实验基准都不一样。而且即便作为baseline，这个超参也要调到最佳参数吧，对于Epinions数据集，SimGCL原文的作者并没有做这个数据集的实验，您直接用原文中的超参，这也明显不合理。


如果有冒犯的地方，还请理解。

**Comment by huachzhou** [comment]
Hi同学您好，mat = mat * values应该是公式4除以根号的，然后expotential作为一个策略就是可以上可以不上，这个expotential加上的话应该收敛比较快，然后Epinions我们没用这个策略。然后用exp的话，我们用的是1/2 * exp()*log(1+exp())来代替exp函数作为一个收敛比较慢的选择，就是协同过滤的流行度去偏如果收敛很快的话，他表征与流行度correlation比较高的。这个是SimGCL去偏效果可能不太好即使recall和NDCG效果非常好，最近有篇work https://arxiv.org/abs/2404.12008讨论了这个问题，当然这一点确实在文章中没有提到，所以把代码放出来可能方便大家更好复现我们的结果。然后有些问题确实没有做的到位，感谢您的批评与指正。
